TemplateEngine improvements, updated template.md
OWASP/pytm pull request #155
Opened 2021-04-08 14:20 UTC by nozmore

I updated the template to showcase #150 and #154. Also expanded template_engine to support the `call` operator with methods that return a list and support to call methods within a report utility class. Updated template.md with examples of each.

Updated tests and ensured tests passed. Also updated report test to write `output_current.md` At some point tests could use this but for now can be used to quickly commit the new `expected` value when the report changes. Added output_current.md` to `.gitignore`

I also added an example in the template.md to get the parents of each Boundary, to see this I updated tm.py with a hierarchy of Boundaries. If we think this is too much for the intro tm.py I can back those changes out.

2021-04-08 14:25 UTC, nozmore commented
oh also added entries in the Data table for carriedBy and processedBy.

2021-04-09 08:43 UTC, nineinchnick requested changes
I'm not convinced we need such a complicated template as an example. I believe it would confuse new users. We should send a clear message that the templating engine in `pytm` is very simple by design, and if it's not enough, users should override it and use a different one.

2021-04-09 08:43 UTC, nineinchnick commented on docs/template.md
> +<br>
I don't think this is necessary. The headers should delimit sections sufficiently.

2021-04-09 08:43 UTC, nineinchnick commented on docs/template.md
> +Parents|{{item.parents:call:{{{{item.name}}}}, }}|
Can't this be a regular table, instead of having a separate table per boundary?

The headers should be human-friendly, that is `InScope` should have space in it.

How people reading the report can tell the difference between `Parent` and `Parents`? Should we only keep `Parents`? Do we need this at all?

2021-04-09 08:43 UTC, nineinchnick commented on docs/template.md
> +Description|{{item.description}}|
Same here, why there's a separate table for each asset? This is inconsistent with existing items, like `Data Dictionary`.

2021-04-09 08:43 UTC, nineinchnick commented on docs/template.md
> +###### Threats
This is duplicated.

2021-04-09 08:43 UTC, nineinchnick commented on docs/template.md
> +&nbsp;
Why is this needed?

2021-04-09 08:43 UTC, nineinchnick commented on pytm/report_util.py
> +    def getParentName(element):
Those should be defined as `@property` in the `Boundary` class.

2021-04-09 08:43 UTC, nineinchnick commented on tests/output.md
> +###### Threats
It should not be a section header unless there would also be one with the element name.

2021-04-09 08:46 UTC, nineinchnick commented on docs/template.md
> +{dataflows:repeat(e):
What does `(e)` in `repeat(e)` do?

2021-04-09 08:47 UTC, nineinchnick commented on docs/template.md
> +{actors:repeat:|{{item.name}}|{{item.description}}|{{item.isAdmin}}|
You're not reporting findings for actors?

2021-04-09 08:49 UTC, nineinchnick commented on docs/template.md
> +Finding Count|{{item:utils:getFindingCount}}|
How did you choose which properties to display? Why not all of them?

2021-04-09 08:50 UTC, nineinchnick commented on docs/template.md
> +Dataflow|{{item.name}}
This should not be a table, but a section header. Data flows not in scope and without any findings should not be displayed.

2021-04-10 16:28 UTC, nozmore commented on docs/template.md
> +<br>
I felt the without the report was visually cluttered. I removed them and used &nbsp;, and made things consistent between each section.

2021-04-10 16:28 UTC, nozmore commented on docs/template.md
> +{actors:repeat:|{{item.name}}|{{item.description}}|{{item.isAdmin}}|
There are no threats for Actors so I didn't include them. I didn't want to add a section for them and give the impression that we could have identified threats but didn't find any by including a 0 count or empty section. 

I can added it with the  `if` operator so that way we don't have to touch this template when/if we add threats to actors.

2021-04-10 16:28 UTC, nozmore commented on docs/template.md
> +Parents|{{item.parents:call:{{{{item.name}}}}, }}|
It could be but I felt with a meaningful description and a list of Parents, add adding overrides and levels would make the table too long for the user and ugly on one-line in source.

InScope, done.

Immediate Parent and All Parents?

2021-04-10 16:28 UTC, nozmore commented on docs/template.md
> +{dataflows:repeat(e):
That was an attempt and altering the variable name but should have removed it, done.

2021-04-10 16:28 UTC, nozmore commented on docs/template.md
> +Dataflow|{{item.name}}
There are unique tables for each dataflow with a Section header for dataflows.

I don't agree, if someone when thru the trouble of modeling them having them visible with their annotations is relevant to understanding the design. I have added if condition to only display the Findings only when findings exist.

2021-04-10 16:28 UTC, nozmore commented on docs/template.md
> +&nbsp;
idk, I cleaned up some of the excess &nbsp; and <br>

2021-04-10 16:28 UTC, nozmore commented on pytm/report_util.py
> +    def getParentName(element):
Personally I think we should keep methods and properties in pytm classes to only be things required for the core logic of pytm. Things like this that are only for reporting and not useful anywhere else should be separate. There is no need anywhere to have a `getParentName` method except using this "template engine", in code you'd just call element.inBoundary.name.

If we think there is another need for any of these functions by all means we should move them in.

2021-04-10 16:28 UTC, nozmore commented on tests/output.md
> +###### Threats
Unfortunately this is the only way in MD to control font size so this what I did. I changed to using bold and it looks fine.

2021-04-10 17:32 UTC, nineinchnick commented on pytm/report_util.py
> +    def getParentName(element):
We use similar helper functions in threat expressions to keep them short. We also have some used in diagrams (display_name, label). I really don't see a problem with adding some more.

But I still think we should not add such a class at all. The template in which you've used this is supposed to be only an example, which imho is too complicated right now.

2021-04-10 17:36 UTC, nineinchnick commented on docs/template.md
> +Parents|{{item.parents:call:{{{{item.name}}}}, }}|
If `All Parents` are sorted, why we need `Immediate Parent` if it's included always as the first or last position?

2021-04-10 17:40 UTC, nineinchnick commented
@nozmore @izar WDYT about keeping two template examples? One simple, one more advanced?

2021-04-10 18:52 UTC, nozmore commented on pytm/report_util.py
> +    def getParentName(element):
Ok I viewed this file differently I see this as the default report the system is able to produce and IMO should eventually be as complete as possible. Thinking about it now, its in `docs` with a sample tm, ok.

To address both we could have a simple template in `docs`, I can use the original report and either 1) use my version in docs with a different name, 2) put it in the root, 3) keep it internal to pytm and add functionality to generate this with an arg for the template isn't provided.

2021-04-10 18:57 UTC, nozmore commented on docs/template.md
> +Parents|{{item.parents:call:{{{{item.name}}}}, }}|
I didn't test or investigate it enough to determine if its consistently sorted. I originally added just Parent and thought I'd save the reader the need to look at all elements to figure out the parent+grandparents and just added the list of all parents.

I have no problem with this but if you feel strongly I can remove Parent and just leave Parents.

2021-04-10 19:04 UTC, nozmore commented
lol I put that in my reply to an earlier comment before reading this. Yes, I think we are viewing this report differently I would prefer to have a fairly complete report and then in `docs` have a simple version to go along with the `simple.tm`

2021-04-10 19:06 UTC, nozmore commented
Why did my tests fail here? Is this executing against the test files in master or in the branch, locally everything passes and I didn't touch DFD logic.

2021-09-28 02:42 UTC, nozmore commented on docs/template.md
> +Parents|{{item.parents:call:{{{{item.name}}}}, }}|
I originally removed Parents and left Parent but I put them back as Immediate Parent and All Parents so that I could have an examples of the templating features.

2021-09-28 03:10 UTC, nozmore commented
Sorry I disappeared, life got in the way. I fixed some issues and cleaned up the reports, merged in master. I think this is ready to be merged.

2021-09-28 08:56 UTC, raphaelahrens commented
Hi,

first I like the change and I wanted to add my thoughts.
Might it be a better idea to have extra repos for reports?
Since a fancy report does not have to be part of the software.
In addition one could also add build instruction and files in the repos which would be solely for the report.
For example I wanted to checkout if I could make a pdf report  and if I find the time I thought about pushing it to a separate repo, which could then be linked to.
Also the users could fork repot to adjust it to their needs (people love company logos and names).

This does not really affect this PR but maybe future PRs which want to change the report template.

2021-09-29 12:39 UTC, izar commented
I like the idea of more complex reports but I think they should go into a directory, not a separate repo, lest the two repos get out of sync version-wise.

2021-10-05 18:00 UTC, nineinchnick commented
I'm still not convinced it's the right thing to do to extend this basic template engine. It's already non-trivial to write advanced templates in it. I vote for replacing it with jinja2.

2021-10-06 00:17 UTC, nozmore commented
> I'm still not convinced it's the right thing to do to extend this basic template engine. It's already non-trivial to write advanced templates in it. I vote for replacing it with jinja2.

If it wasn't already done I'd agree. Its done, functional, adds minimal changes to the engine, and moves pytm forward. Replacing with another library can still be done later or use something to render the JSON output.

This is my only open source project, how to tie breakers work?

2021-10-06 06:12 UTC, nineinchnick commented
> > I'm still not convinced it's the right thing to do to extend this basic template engine. It's already non-trivial to write advanced templates in it. I vote for replacing it with jinja2.
> 
> If it wasn't already done I'd agree. Its done, functional, adds minimal changes to the engine, and moves pytm forward. Replacing with another library can still be done later or use something to render the JSON output.
> 
> This is my only open source project, how to tie breakers work?

I don't agree that changes proposed here are minimal.
@izar has they final word here. I can disagree and commit.

2021-10-11 19:15 UTC, izar commented
Sorry for the late reply, I am a bit overwhelmed these days.
I am reluctant to move into something like jinja2, even though I like it -
I fear we "get married" to it moving forward, but it is a bit of an
unfounded worry. I can't put my finger on it, but something bothers me.
Here's what I propose - as @nozmore says, it is done. How about we move
forward with this patch, and on the next "the template engine doesn't do X"
we reassess - if jinja2 or some other engine do it and we find out the move
is "easy" we go that way, otherwise we continue with this implementation.
Acceptable compromise?

Btw, I don't have the final word. I value you guys' opinion very much and I
will never overrule a good argument, especially considering how much I
always learn from each one of you. We are a democratic team.


On Wed, Oct 6, 2021 at 2:13 AM Jan Waś ***@***.***> wrote:

> I'm still not convinced it's the right thing to do to extend this basic
> template engine. It's already non-trivial to write advanced templates in
> it. I vote for replacing it with jinja2.
>
> If it wasn't already done I'd agree. Its done, functional, adds minimal
> changes to the engine, and moves pytm forward. Replacing with another
> library can still be done later or use something to render the JSON output.
>
> This is my only open source project, how to tie breakers work?
>
> I don't agree that changes proposed here are minimal.
> @izar <https://github.com/izar> has they final word here. I can disagree
> and commit.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/izar/pytm/pull/155#issuecomment-935547036>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAC2BALUMVVHP4UKBYQ3BF3UFPSHFANCNFSM42S74TRA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-13 01:58 UTC, nozmore commented on pytm/report_util.py
> +    def getParentName(element):
Previously added a basic and advanced template which addresses some of the comments here. 

Since we have talked about eventually replacing this template system with something else I think using this class is a better option for logic added only due to limitations in this templating system and will make it easier to remove if/when we move to something more advanced, rather than cluttering up the various classes with property methods that won't be needed.

2021-10-13 02:03 UTC, nozmore commented
Sounds good to me. I don't have plans to add any additional logic to the templating system. That said I do see additions to either the various internal classes or the report_util class when data needs to be formatted in a way for reporting. 

For example the PR about custom properties using a dict, I have a method drafted locally that I will push to report_util once the template changes are merged that will enable looping over the dict and prevent KeyError exceptions when the key does not exist in the dict.

2021-10-29 17:51 UTC, nozmore commented on pytm/report_util.py
> +    def getParentName(element):
Marking as resolved. I added separated out the templates as requested and responded to the comments about using the helper class.

2021-10-31 14:16 UTC, merged